import type { RaycastAIModels } from '@ru/shared'

export const OPENAI_SERVICE_PROVIDERS: RaycastAIModels = [
  {
    id: 'openai-gpt-3.5-turbo',
    description: 'GPT-3.5 Turbo from OpenAI',
    model: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    features: ['chat', 'quick_ai', 'commands', 'api', 'emoji_search'],
    speed: 3,
    intelligence: 3,
    provider: 'openai',
    provider_name: 'OpenAI',
    provider_brand: 'openai',
    requires_better_ai: false,
    context: 16,
    capabilities: { },
    suggestions: ['chat', 'quick_ai', 'commands'],
    in_better_ai_subscription: false,
    status: null,
  },
  {
    id: 'openai-gpt-4-turbo',
    description: 'GPT-4 Turbo from OpenAI',
    model: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    features: ['chat', 'quick_ai', 'commands', 'api', 'emoji_search'],
    speed: 3,
    intelligence: 3,
    provider: 'openai',
    provider_name: 'OpenAI',
    provider_brand: 'openai',
    requires_better_ai: true,
    context: 16,
    capabilities: { },
    suggestions: ['chat', 'quick_ai', 'commands'],
    in_better_ai_subscription: false,
    status: null,
  },
  {
    id: 'openai-gpt-4o',
    description: 'GPT-4o from OpenAI',
    model: 'gpt-4o',
    name: 'GPT-4o',
    features: ['chat', 'quick_ai', 'commands', 'api', 'emoji_search'],
    speed: 3,
    intelligence: 3,
    provider: 'openai',
    provider_name: 'OpenAI',
    provider_brand: 'openai',
    requires_better_ai: true,
    context: 16,
    capabilities: { },
    suggestions: ['chat', 'quick_ai', 'commands'],
    in_better_ai_subscription: false,
    status: null,
  },
  {
    id: 'openai-gpt-4o-mini',
    description: 'GPT-4o-mini from OpenAI',
    model: 'gpt-4o-mini',
    name: 'GPT-4o-mini',
    features: ['chat', 'quick_ai', 'commands', 'api', 'emoji_search'],
    speed: 3,
    intelligence: 3,
    provider: 'openai',
    provider_name: 'OpenAI',
    provider_brand: 'openai',
    requires_better_ai: true,
    context: 16,
    capabilities: { },
    suggestions: ['chat', 'quick_ai', 'commands'],
    in_better_ai_subscription: false,
    status: null,
  },
  {
    id: 'openai-gpt-o1',
    description: 'GPT-o1 from OpenAI',
    model: 'o1',
    name: 'GPT-o1',
    features: ['chat', 'quick_ai', 'commands', 'api', 'emoji_search'],
    speed: 3,
    intelligence: 3,
    provider: 'openai',
    provider_name: 'OpenAI',
    provider_brand: 'openai',
    requires_better_ai: true,
    context: 16,
    capabilities: { },
    suggestions: ['chat', 'quick_ai', 'commands'],
    in_better_ai_subscription: false,
    status: null,
  },
  {
    id: 'openai-gpt-o3-mini',
    description: 'GPT-o3-mini from OpenAI',
    model: 'o3-mini',
    name: 'GPT-o3-mini',
    features: ['chat', 'quick_ai', 'commands', 'api', 'emoji_search'],
    speed: 3,
    intelligence: 3,
    provider: 'openai',
    provider_name: 'OpenAI',
    provider_brand: 'openai',
    requires_better_ai: true,
    context: 16,
    capabilities: { },
    suggestions: ['chat', 'quick_ai', 'commands'],
    in_better_ai_subscription: false,
    status: null,
  },
]

export const GROQ_SERVICE_PROVIDERS: RaycastAIModels = [

]

export const GEMINI_SERVICE_PROVIDERS: RaycastAIModels = [
  {
    id: 'gemini-pro',
    model: 'gemini-pro',
    name: 'Gemini Pro',
    description: `Gemini Pro is a Google's model. It's a foundation model that performs well at a variety of natural language tasks such as summarization, instruction following, content generation, sentiment analysis, entity extraction, classification etc`,
    provider: 'gemini',
    provider_name: 'Google',
    provider_brand: 'google',
    requires_better_ai: false,
    speed: 3,
    intelligence: 3,
    context: 16,
    suggestions: ['chat', 'quick_ai', 'commands'],
    features: ['chat', 'quick_ai', 'commands', 'api'],
    capabilities: {
      // image_generation: 'null',
      // web_search: 'null'
    },
    in_better_ai_subscription: false,
    status: 'beta',
  },
]

export const COHERE_SERVICE_PROVIDERS: RaycastAIModels = [
  {
    id: 'command-r',
    model: 'command-r',
    name: 'Command R',
    description: `Command R is an instruction-following conversational model that performs language tasks at a higher quality, more reliably, and with a longer context than previous models. It is best suited for complex workflows like code generation, retrieval augmented generation (RAG), tool use, and agents.`,
    provider: 'cohere',
    provider_name: 'Cohere',
    provider_brand: 'openai',
    requires_better_ai: false,
    speed: 3,
    intelligence: 3,
    context: 128,
    suggestions: [],
    features: ['chat', 'quick_ai', 'commands', 'api', 'emoji_search'],
    capabilities: {
      // image_generation: 'null',
      web_search: 'full',
    },
    in_better_ai_subscription: false,
    status: null,
  },
  {
    id: 'command-r-plus',
    model: 'command-r-plus',
    name: 'Command R+',
    description: `Command R+ is an instruction-following conversational model that performs language tasks at a higher quality, more reliably, and with a longer context than previous models. It is best suited for complex RAG workflows and multi-step tool use.`,
    provider: 'cohere',
    provider_name: 'Cohere',
    provider_brand: 'openai',
    requires_better_ai: false,
    speed: 3,
    intelligence: 3,
    context: 128,
    suggestions: ['chat', 'quick_ai', 'commands'],
    features: ['chat', 'quick_ai', 'commands', 'api', 'emoji_search'],
    capabilities: {
      // image_generation: 'null',
      web_search: 'full',
    },
    in_better_ai_subscription: false,
    status: null,
  },
  {
    id: 'c4ai-aya-23',
    model: 'c4ai-aya-23',
    name: 'C4AI Aya 23',
    description: `C4AI Aya 23 is a research open weights release of an 8 and 35 billion parameter with highly advanced instruction fine-tuned model, covering 23 languages.\nNote: Aya 23 is a single-turn instruction-following model and it is not optimized for chat mode use.\n`,
    provider: 'cohere',
    provider_name: 'Cohere',
    provider_brand: 'openai',
    requires_better_ai: false,
    speed: 4,
    intelligence: 3,
    context: 8,
    suggestions: ['quick_ai'],
    features: ['chat', 'quick_ai', 'commands', 'api', 'emoji_search'],
    capabilities: {},
    in_better_ai_subscription: false,
    status: null,
  },
]

export const RAYCAST_DEFAULT_MODELS = {
  chat: 'openai-gpt-4o-mini',
  quick_ai: 'openai-gpt-4o-mini',
  commands: 'openai-gpt-4o-mini',
  api: 'openai-gpt-4o-mini',
  emoji_search: 'openai-gpt-4o-mini',
}

export const RAYCAST_GEMINI_PRO_ONLY_MODELS = {
  chat: 'gemini-pro',
  quick_ai: 'gemini-pro',
  commands: 'gemini-pro',
  api: 'gemini-pro',
  emoji_search: 'gemini-pro',
}

export const RAYCAST_DEFAULT_GROQ_MODELS = {
  chat: 'llama3-70b-8192',
  quick_ai: 'llama3-70b-8192',
  commands: 'llama3-70b-8192',
  api: 'llama3-70b-8192',
  emoji_search: 'llama3-70b-8192',
}

export const OPENAI_OFFICIAL_ENDPOINT = 'https://api.openai.com/v1/chat/completions'
export const GEMINI_OFFICIAL_ENDPOINT = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent'
